//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIntegration.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class parent
    {
        public int id { get; set; }
        public string parentname { get; set; }
        public int parenttype { get; set; }
    }
}
