//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFIntegration.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TESTEntities : DbContext
    {
        public TESTEntities()
            : base("name=TESTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Customer_Backup> Customer_Backup { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<parent> parents { get; set; }
        public virtual DbSet<SomeTable> SomeTables { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<studentparent> studentparents { get; set; }
        public virtual DbSet<TABLEONE> TABLEONEs { get; set; }
        public virtual DbSet<TABLETWO> TABLETWOes { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<vw_studentInfo> vw_studentInfo { get; set; }
    
        public virtual int SP_CREATE_STUDENT_PARENT(string sTUDENTNAME, string fATHERNAME, string mOTHERNAME)
        {
            var sTUDENTNAMEParameter = sTUDENTNAME != null ?
                new ObjectParameter("STUDENTNAME", sTUDENTNAME) :
                new ObjectParameter("STUDENTNAME", typeof(string));
    
            var fATHERNAMEParameter = fATHERNAME != null ?
                new ObjectParameter("FATHERNAME", fATHERNAME) :
                new ObjectParameter("FATHERNAME", typeof(string));
    
            var mOTHERNAMEParameter = mOTHERNAME != null ?
                new ObjectParameter("MOTHERNAME", mOTHERNAME) :
                new ObjectParameter("MOTHERNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_STUDENT_PARENT", sTUDENTNAMEParameter, fATHERNAMEParameter, mOTHERNAMEParameter);
        }
    
        public virtual ObjectResult<sp_studentParent_Result> sp_studentParent()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_studentParent_Result>("sp_studentParent");
        }
    }
}
